create database project2;

select * from mydata limit 10;

-- 1 what is the total revenue generated by male and female
select gender, sum(purchase_amount) as 'total revenue' from mydata
group by gender;


-- 2 which customers used discount but still spent more than average purchase amount
select customer_id,purchase_amount from mydata where discount_applied ='yes' and purchase_amount > (select avg(purchase_amount) from mydata);

-- 3 which are top 5 products with highest average review rating
select item_purchased, round(avg(review_rating),2) from mydata
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- 4. compare the avg purchase amounts between standard and express shipping
select shipping_type, avg(purchase_amount) from mydata
where shipping_type in ('Express', 'Standard') 
group by shipping_type;

-- 5. do subscribed customers spend more? compare avg spend and total revenue btween subscribers and non subscribers
select subscription_status,count(customer_id), avg(purchase_amount),sum(purchase_amount) from mydata
group by subscription_status;

-- 6.which products have the highest percentage of purchases with discounts applied
SELECT item_purchased,COUNT(*) AS total_purchases,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
    ROUND(
        (SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)), 2
    ) AS discount_percentage
FROM mydata
GROUP BY item_purchased
ORDER BY discount_percentage DESC
Limit 5;

-- 7  sgment customers based into returning ,new,loyal based on no.of prev purchases and show count of each segment

with new as(select customer_id,
case
when previous_purchases = 1 then 'new'
when previous_purchases < 20 then 'returning'
else 'loyal'
end as customer_returnings
from mydata)
select count(*),customer_returnings from new
group by customer_returnings;

-- 8 what are top3 most purchased products in each category
select item_purchased, category,total from ( select item_purchased,category, count(*) as total, row_number() over (partition by category order by count(*) desc) as rn from mydata group by item_purchased, category)t where rn<=3;

-- 9 are customers who are repeat buyers also likely to subscribe
select subscription_status, count(customer_id) from mydata
where previous_purchases >=20
group by subscription_status;


-- 10 what is revenue contribution of each age group
select age_group,sum(purchase_amount) from mydata
group by age_group
order by sum(purchase_amount )desc;

